Add a libcnb tutorial
buildpacks/libcnb pull request #242
Opened 2023-06-23 08:14 UTC by AidanDelaney

Outline how to implement `Detect` and `Build` using a motivating example.

2023-06-23 13:00 UTC, dmikusa requested changes
This is great! Thanks for writing this up.

I think it's missing an intro on how to create the project files. It would be awesome to showcase the pack functionality to create a new buildpack project here. 

I think it's also missing instructions on how to build and package the buildpack. Something needs to compile the go into binary files & then you have to run `pack buildpack package`.

2023-06-28 05:00 UTC, AidanDelaney commented on docs/detect.md
> +However, it is often the case that a `detect` binary passes even if some file is not found.  In such a case the buildpack is passing if the file is found or if the file is not found.  This allows the
Thanks.  You're completely correct.  I've now removed this discussion to avoid the rabbit-hole.

2023-06-28 05:12 UTC, AidanDelaney commented on docs/build.md
> +The `detect` phases passes metadata to the `build` phase in the [`BuildpackPlan`](https://pkg.go.dev/github.com/buildpacks/libcnb#BuildpackPlan) (note: not to be confused with the more general [`Buil
I've removed `libpak` as a dependency here.  I have not removed the use of `libpak.crush` to extract the archive.

2023-06-28 12:28 UTC, dmikusa commented on docs/build.md
> +To contribute a layer we implement the [`LayerContributor`](https://pkg.go.dev/github.com/buildpacks/libcnb#LayerContributor) interface.  Our `Contributor` will download an archive from the provided
```suggestion
To contribute a layer we implement the [`LayerContributor`](https://pkg.go.dev/github.com/buildpacks/libcnb#LayerContributor) interface.  Our `Contributor` will download an archive from the provided URL.  Again, we borrow a utility function from `libpak` to extract the archive to an output layer. You could use standard Go archive functions to do this, but it's more work.
```

2023-06-28 12:29 UTC, dmikusa approved these changes
I sent you one more minor suggestion, but overall it looks good and I'm approving.

2023-10-04 12:43 UTC, merged